### ISSUE TITLE
[enhancement]: add gif bg support 

### ISSUE THREAD

**Issue by T-Dynamos** [kivy-garden/frostedglass#12]
I see currently no support of gif.
And seeing uncanny blur without animation (on frostedglass master)
![Screenshot_20230526_134719](https://github.com/kivy-garden/frostedglass/assets/68729523/495ead40-172f-4f47-a5b4-eb0293f73e69)

main.py:
```python
import _thread

from kivy.config import Config
# Initially hide it
Config.set("graphics", "window_state", "hidden")

from kivy.lang import Builder
from kivy.app import App
from kivy.clock import Clock
from kivy.core.window import Window
from kivy_garden.frostedglass import FrostedGlass

from materialyoucolor.utils.theme_utils import (
    themeFromSourceColor,
    getDefaultTheme,
    getDominantColors,
)
from materialyoucolor.utils.string_utils import argbFromRgb, hexFromArgb

IMAGE = "/home/tdynamos/test2.gif"
MODE = "light"
INDEX = 0
OUTLINE_ALPHA = 0
OVERLAY_ALPHA = 0.5

class Main(App):
    image = IMAGE

    def build(self):
        return Builder.load_file("main.kv")

    def on_start(self):
        _thread.start_new_thread(self.get_colors, ())

    def kivy_color(self, rgb, alpha=1):
        return [rgb[0] / 256, rgb[1] / 256, rgb[2] / 256, alpha]

    def get_colors(self):
        colors = getDominantColors(self.image)
        theme_colors = themeFromSourceColor(colors[INDEX])["schemes"][MODE].props
        Clock.schedule_once(
            lambda arg: self.update_colors(
                self.kivy_color(theme_colors["primary"], alpha=OVERLAY_ALPHA),
                self.kivy_color(theme_colors["outline"], alpha=OUTLINE_ALPHA),
            )
        )

    def update_colors(self, main, outline):
        self.root.ids.glass.overlay_color = main
        self.root.ids.outline_color = outline
        Window.show()


Main().run()
```
(Install materialyoucolor from https://github.com/T-Dynamos/materialyoucolor-pyhton)
main.kv
```kvlang
RelativeLayout:
    Image:
        id:bg
        source:app.image
        fit_mode:"cover"
        anim_delay:0.05 
    FrostedGlass:
        id:glass
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        size_hint: 0.5, 0.5
        background:bg
        blur_size: 20
        saturation: 1.0
        luminosity: 1.2
        noise_opacity: 0.01
        border_radius:  [dp(20)] * 4
        outline_color: 0,0,0,.4
        outline_width: dp(0.8)
```
gif:
![test2](https://github.com/kivy-garden/frostedglass/assets/68729523/ed86f7a2-002f-45a6-96e8-a59c28451803)

**Comment by DexerBR** [comment]
Hi @T-Dynamos!

This feature already existed in version `0.3.0`, but it was accidentally broken in version `0.4.0`.

This [PR ](https://github.com/kivy-garden/frostedglass/pull/13)fixes that!

**Comment by DexerBR** [comment]
Thanks for the issue, resolved via #12 (now merged into the `develop` branch).

**Comment by T-Dynamos** [comment]
@DexerBR 
![Screenshot_20230528_201146](https://github.com/kivy-garden/frostedglass/assets/68729523/4edaf1cb-e30b-48a2-b519-a1551fa08b72)
But when using image:
![Screenshot_20230528_202258](https://github.com/kivy-garden/frostedglass/assets/68729523/719f4a6a-063d-4a38-9c29-8600beec9faf)

This blur is not yet fixed.

**Comment by DexerBR** [comment]
> @DexerBR ![Screenshot_20230528_201146](https://user-images.githubusercontent.com/68729523/241567345-4edaf1cb-e30b-48a2-b519-a1551fa08b72.png) But when using image: ![Screenshot_20230528_202258](https://user-images.githubusercontent.com/68729523/241568038-719f4a6a-063d-4a38-9c29-8600beec9faf.png)
> 
> This blur is not yet fixed.

I understood. This is actually a different issue and requires some updates to the way the blur is handled. Possibly it will be something to be done in a next release.

In the meantime, you can choose a smaller value for the `blur_size`, and this unwanted effect will be much less noticeable.

@T-Dynamos Would you mind opening a new issue so we can track this it more cleanly?

**Comment by DexerBR** [comment]
@T-Dynamos Spoiler: This occurs with images that have image elements drawn completely horizontally and/or vertically (as in the first image)
